---
- name: Create Project Directory
  ansible.builtin.file:
    path:  "./collections/ansible_collections/{{ project_dir }}"
    state: directory

- name: Clone Ansible Project Repository
  ansible.builtin.include_role:
    name: demos.utils.git
  vars:
    git_repository: "{{ project_git_url }}"
    git_directory: "./collections/ansible_collections/{{ project_dir }}"
    git_operation: clone
  register: git_result

- name: Create extensions directory in the content collection
  ansible.builtin.file:
    path: "./collections/ansible_collections/{{ project_dir }}/extensions"
    state: directory

