---
- name: "Linting files"
  ansible.builtin.shell: |
    unset ANSIBLE_COLLECTIONS_PATHS
    ansible-lint -p -q -f json
  args:
    chdir: "./collections/ansible_collections/{{ project_dir }}"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections"
  register: lint_results

- debug: msg="{{ lint_results | to_json }}"

