---
- name: Find tasks files
  ansible.builtin.find:
    file_type: directory
    patterns: "tasks"
    recurse: true
    paths: "."
  register: tasks_files

- name: Lint found files
  ansible.builtin.shell: "ansible-lint {{ item.path }}"
  loop: "{{ tasks_files.files }}"

