---
- name: "Linting files"
  ansible.builtin.shell: |
    unset ANSIBLE_COLLECTIONS_PATHS
    ansible-lint -p -q -f json {{ item.path }}
  loop: "{{ roles_directories.files }}"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections/{{ project_dir }}/extensions"
  register: lint_results

- debug: msg="{{ lint_results | to_json }}"

