---
- name: Find tasks directories
  ansible.builtin.find:
    file_type: directory
    patterns: "tasks"
    recurse: true
    paths: "."
  register: roles_directories

- name: Find tasks files
  ansible.builtin.find:
    file_type: file
    recurse: true
    paths: "{{ item.path }}"
  register: tasks_files
  loop: "{{ roles_directories.files }}"

- debug: msg="{{ tasks_files.results }}"

- name: Lint found files
  ansible.builtin.shell: |
    unset ANSIBLE_COLLECTIONS_PATHS
    ansible-lint -p {{ item.files[0].path }}
  loop: "{{ tasks_files.results }}"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections/{{ project_dir }}/extensions"

