---
- name: Prepare environment
  ansible.builtin.include_tasks: clone.yml

- name: Perform Molecule Tests
  ansible.builtin.include_tasks: molecule.yml

- name: Perform Molecule Tests
  ansible.builtin.include_tasks: lint.yml
