---
- name: Perform tests
  ansible.builtin.shell: |
    unset ANSIBLE_COLLECTIONS_PATHS
    molecule init scenario
    molecule test
    exit 0
  args:
    chdir: "./collections/ansible_collections/{{ project_dir }}/extensions"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections/{{ project_dir }}/extensions"
