---
- name: Init Molecule Scenario
  ansible.builtin.shell: |
    unset ANSIBLE_COLLECTIONS_PATHS
    molecule init scenario
  args:
    chdir: "./collections/ansible_collections/{{ project_dir }}/extensions"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections/{{ project_dir }}/extensions"

- name: Perform tests
  ansible.builtin.shell: |
    unset ANSIBLE_COLLECTIONS_PATHS
    molecule test idempotence
  args:
    chdir: "./collections/ansible_collections/{{ project_dir }}/extensions"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections/{{ project_dir }}/extensions"

