---
- name: Unset ANSIBLE_COLLECTIONS_PATH
  command: unset ANSIBLE_COLLECTIONS_PATH
  environment: 
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Initialize scenario
  ansible.builtin.command: molecule init scenario
  args:
    chdir: "./collections/ansible_collections/{{ project_dir }}/extensions"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections/{{ project_dir }}/extensions"

- name: Perform molecule tests
  ansible.builtin.command: molecule test
  args:
    chdir: "{{ project_dir }}"
    