---
- name: Initialize scenario
  ansible.builtin.command: molecule init scenario --driver-name podman
  args:
    chdir: "{{ project_dir }}"

- name: Perform molecule tests
  ansible.builtin.command: molecule test
  args:
    chdir: "{{ project_dir }}"
    