---
- name: Unset ANSIBLE_COLLECTIONS_PATH
  ansible.builtin.shell: "unset ANSIBLE_COLLECTIONS_PATHS"

- name: Initialize scenario
  ansible.builtin.command: molecule init scenario
  args:
    chdir: "./collections/ansible_collections/{{ project_dir }}/extensions"
  environment:
    ANSIBLE_COLLECTIONS_PATH: "./collections/ansible_collections/{{ project_dir }}/extensions"

- name: Perform molecule tests
  ansible.builtin.command: molecule test
  args:
    chdir: "{{ project_dir }}"
    