---
- name: Pass molecule tests to an Ansible Collection
  hosts: all
  gather_facts: true
  tasks:
    - name: Get current date
      ansible.builtin.set_fact:
        operation_time: "{{ ansible_date_time.iso8601_basic_short }}"

    - name: Clone Configuration Repository
      ansible.builtin.include_role:
        name: demos.utils.git
      vars:
        git_repository: "{{ repository }}"
        git_directory: "/tmp/{{ operation_time }}"
        git_operation: clone
      register: git_result

    - command: ls -la /tmp/{{ operation_time }}/extensions

    - name: Execute molecule tests
      ansible.builtin.command: molecule test 
      args:
        chdir: /tmp/{{ operation_time }}/extensions
      register: molecule_results
      changed_when: molecule_results.rc == 0
